### ISSUE TITLE
Seperate Uploaded PS3 and PSvita Images

### ISSUE THREAD

**Issue by Arcadius2006** [LBPUnion/ProjectLighthouse#244] opened 2022-03-17 22:33 UTC
PS3 images do not display correctly on PSvita and vice versa, as a way to combat this, the server should seperate images into PS3 and PSvita

in addition: profile pages should have an option to switch between viewing the PS3 and vita profile picture and maybe other things
![image](https://user-images.githubusercontent.com/93880348/158904783-82ca3736-d387-4139-af29-06db4a4df0e8.png)
![image](https://user-images.githubusercontent.com/93880348/158905329-2e69a630-e796-42ed-ae6e-68000a17bf9b.png)

**Comment by Arcadius2006** [comment] 2022-03-17 22:38
also, this suggestion is exclusively for images, things such as levels and comments dont need to be seperated

**Comment by jvyden** [comment] 2022-03-18 18:53
This is a workaround to the problem, not an actual solution.

Also a duplicate of #207.

**Closed by jvyden** 2022-03-18 18:53 UTC
