### ISSUE TITLE
LittleBigPlanet 3 Beta cannot do anything online besides the ability to connect to friends. 

### ISSUE THREAD

**Issue by Hyphen-Tilda** [LBPUnion/ProjectLighthouse#701] opened 2023-03-10 00:38 UTC
Console: PS3
Game Affected: LittleBigPlanet™3 Digital Version BETA
I cannot and never have been able to do any online thing on LittleBigPlanet 3 Beta on Beacon, with the exception of joining and inviting my friend heinp193. Online features like viewing profiles take a noticeable amount of time to load and fail. 
In the future, could this problem be eradicated and cause LBP3 Beta to be more online capable?

**Comment by Slendy** [comment] 2023-03-10 00:48
Can you provide the specific revision you are using? It should be on the bottom left of the screen and look something like this.
![image](https://user-images.githubusercontent.com/16675503/224194714-c3af900f-abc6-4841-a446-e253bde12fa4.png)

**Comment by Hyphen-Tilda** [comment] 2023-03-10 02:06
> Can you provide the specific revision you are using? It should be on the bottom left of the screen and look something like this.
> ![image](https://user-images.githubusercontent.com/16675503/224194714-c3af900f-abc6-4841-a446-e253bde12fa4.png)
Unfortunately it doesn't seem like LBP3 Beta has that revision text during gameplay.

**Comment by LBPHaxMods** [comment] 2023-03-10 23:09
I went through the eboot, and the revision the private beta uses is **619919**

**Comment by LBPHaxMods** [comment] 2023-03-11 02:56
Also I just remembered, this is because the LBP3 Beta uses a different digest key, I'm fairly sure you can modify the EBOOT to use the retail digest key.

**Comment by Arcadius2006** [comment] 2023-03-13 11:31
silly Hyphen-Tilda!

**Comment by Arcadius2006** [comment] 2023-03-18 13:51
why is this still open

**Comment by sudokoko** [comment] 2023-03-18 15:15
> Also I just remembered, this is because the LBP3 Beta uses a different digest key, I'm fairly sure you can modify the EBOOT to use the retail digest key.

This seems to be the cause of the issue, closing this for now.

**Closed by sudokoko** 2023-03-18 15:15 UTC
Labels: bug, server:gameserver
