### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by o0ent** [LBPUnion/ProjectLighthouse#301] opened 2022-05-08 06:32 UTC
`
System.NullReferenceException: Object reference not set to an instance of an object.
at LBPUnion.ProjectLighthouse.Logging.Logger.getTrace(Int32 extraTraceLines) in C:\Users\*****\Desktop\lighthouse\ProjectLighthouse\ProjectLighthouse\Logging\Logger.cs:line 60
at LBPUnion.ProjectLighthouse.Helpers.FileHelper.ConvertAllTexturesToPng() in C:\Users\*****\Desktop\lighthouse\ProjectLighthouse\ProjectLighthouse\Helpers\FileHelper.cs:line 117
at LBPUnion.ProjectLighthouse.Program.Main(String[] args) in C:\Users\*****\Desktop\lighthouse\ProjectLighthouse\ProjectLighthouse\Program.cs:line 75
`

**Comment by metraberryy** [comment] 2022-05-08 11:40
getting this same error, glad it wasnt my fault

**Comment by metraberryy** [comment] 2022-05-08 11:43
looks to do with this commit ? https://github.com/LBPUnion/ProjectLighthouse/commit/1d5d8cb51402683e3eac912fe908f95bd1cdd75d

**Comment by o0ent** [comment] 2022-05-09 09:31
change ConvertAssetsOnStartup to false

**Comment by jvyden** [comment] 2022-05-14 18:04
I can't reproduce this issue. It's also interesting how you aren't hitting the assertion on line 55. Can you attach a debugger and show me what's null here?

**Comment by jvyden** [comment] 2022-05-14 18:05
> change ConvertAssetsOnStartup to false

Not a solution.

**Comment by o0ent** [comment] 2022-05-15 05:49
with debug mode its start successfully, i only gets this errors (sorry for my english)
```
Error while converting 43d2e9247b96741b94a2630628e9dea2d4517b86:
ICSharpCode.SharpZipLib.SharpZipBaseException: Header checksum illegal
at ICSharpCode.SharpZipLib.Zip.Compression.Inflater.DecodeHeader()
at ICSharpCode.SharpZipLib.Zip.Compression.Inflater.Decode()
at ICSharpCode.SharpZipLib.Zip.Compression.Inflater.Inflate(Byte[] buffer, Int32 offset, Int32 count)
at ICSharpCode.SharpZipLib.Zip.Compression.Inflater.Inflate(Byte[] buffer)
at LBPUnion.ProjectLighthouse.Helpers.ImageHelper.TextureToPNG(String hash, BinaryReader reader) in C:\Users\*****\Desktop\lighthouse\ProjectLighthouse\ProjectLighthouse\Helpers\ImageHelper.cs:line 80
```

**Comment by metraberryy** [comment] 2022-05-15 13:10
not having this anymore on the latest commit

**Comment by jvyden** [comment] 2022-05-15 14:37
> with debug mode its start successfully, i only gets this errors (sorry for my english)
> 
> ```
> Error while converting 43d2e9247b96741b94a2630628e9dea2d4517b86:
> ICSharpCode.SharpZipLib.SharpZipBaseException: Header checksum illegal
> at ICSharpCode.SharpZipLib.Zip.Compression.Inflater.DecodeHeader()
> at ICSharpCode.SharpZipLib.Zip.Compression.Inflater.Decode()
> at ICSharpCode.SharpZipLib.Zip.Compression.Inflater.Inflate(Byte[] buffer, Int32 offset, Int32 count)
> at ICSharpCode.SharpZipLib.Zip.Compression.Inflater.Inflate(Byte[] buffer)
> at LBPUnion.ProjectLighthouse.Helpers.ImageHelper.TextureToPNG(String hash, BinaryReader reader) in C:\Users\*****\Desktop\lighthouse\ProjectLighthouse\ProjectLighthouse\Helpers\ImageHelper.cs:line 80
> ```

These errors can be ignored.

Closing as solved.

**Closed by jvyden** 2022-05-15 14:37 UTC
Labels: bug
