### ISSUE TITLE
Timezone dropdown menu is in foreign language when website is set to English

### ISSUE THREAD

**Issue by Salamni** [LBPUnion/ProjectLighthouse#805] opened 2023-06-18 06:43 UTC
Was gonna change my timezone, then saw that only the timezone dropdown was in Spanish 😭 

To reproduce, as this might be an issue on my side, just go to settings on your profile and click "Timezone"

![image](https://github.com/LBPUnion/ProjectLighthouse/assets/90370947/23c84002-f7e9-48ae-93b7-2a258869a5a0)

**Comment by Slendy** [comment] 2023-06-18 06:54
Closing as this is a duplicate of #672.

**Closed by Slendy** 2023-06-18 06:54 UTC
Labels: bug
