### ISSUE TITLE
Users page filter our fake users, disallow fake commenters, and limit user creation

### ISSUE THREAD

**Issue by FridiNaTor1** [LBPUnion/ProjectLighthouse#203] opened 2022-02-26 23:50 UTC
There should be a check for when a User is made that it doesn't appear on the Users page until they actually have logged into one of the games. Also should disallow new users that haven't logged into any game before, to comment on profiles/levels on the website. This is to prevent trolls, fake users, etc.

There should also be a check on IP address how many accounts are being made. Admin can make as many accounts without limitation. But the normal user should only be able to make 4 a week or something (4 because it's possible they could make 4 accounts one for them and 3 for friends or family). This should also prevent people from mass creating fake accounts.

**Comment by turecross321** [comment] 2022-02-27 17:04
You mean something like this https://github.com/LBPUnion/ProjectLighthouse/issues/78?

**Comment by jvyden** [comment] 2022-02-27 19:18
Duplicate of #78, and #186.

**Closed by jvyden** 2022-02-27 19:18 UTC
