### ISSUE TITLE
Add in-game filtering

### ISSUE THREAD

**Issue by Arcadius2006** [LBPUnion/ProjectLighthouse#272] opened 2022-04-09 17:39 UTC
an extension to #233 - in LittleBigPlanet 2 and 3 there are options to filter levels via game, label and how many players the level requires. we should implement this to make matchmaking much easier

**Comment by jvyden** [comment] 2022-04-09 22:22
Duplicate of #90

**Closed by jvyden** 2022-04-09 22:22 UTC
