### ISSUE TITLE
Show Queued levels on website

### ISSUE THREAD

**Issue by Leafar70** [LBPUnion/ProjectLighthouse#240] opened 2022-03-12 13:54 UTC
I wonder if in the website, in your profile section, there could be a button that show all the levels you have in your queue, if you have any.

**Comment by Slendy** [comment] 2022-03-12 16:03
Duplicate of #151

**Closed by Slendy** 2022-03-12 16:03 UTC

**Comment by Leafar70** [comment] 2022-03-12 16:24
Oh, sorry, I didnt see there was already an issue of it
